### ISSUE TITLE
Plans to contribute driver to main GDAL trunk?

### ISSUE THREAD

**Issue by m9brady** [DND-DRDC-RDDC/OS_DriverMetadataExtractionCodes_RCM_C-band_SARdata#1]
This is fantastic and very exciting work. Are there plans to submit this driver as a PR back to GDAL? 

https://github.com/OSGeo/gdal

See also https://github.com/OSGeo/gdal/issues/4065

**Comment by ShawnGong3** [comment]
Yes, it is our plan to submit this driver back to GDAL.
